### ISSUE TITLE
[Feat] 홈뷰에서 수정뷰 전환

### ISSUE THREAD

**Issue by jeongdung-eo** [DO-NOTTO-DO/iOS-NOTTODO#134]
## 🍏 Issue
- 홈뷰 스와이프 눌렀을 때 수정뷰로 전환
## 📝 To-do

- [ ] 홈뷰에서 수정뷰로 전환
- [ ] 수정뷰 API 추가
- [ ] 홈디테일 코드 수정
