### ISSUE TITLE
[Fix] 생성/수정 뷰 날짜 선택 UI 및 스와이프 화면전환 시 날짜 Text 수정

### ISSUE THREAD

**Issue by yungu0010** [DO-NOTTO-DO/iOS-NOTTODO#136]
## 🍏 Issue

- 토글을 열었을 때 선택된 날짜 유지 되도록 수정
- 스와이프에서 낫투두 수정 날짜 텍스트 수정
- 낫투두 수정 navigationTitle 수정

## 📝 To-do

- [ ] 토글을 열었을 때 선택된 날짜 유지 되도록 수정
- [ ] 스와이프에서 낫투두 수정 날짜 텍스트 수정
- [ ] 낫투두 수정 navigationTitle 수정
