### ISSUE TITLE
[Fix] 생성/수정 뷰 키보드 액션처리 수정

### ISSUE THREAD

**Issue by yungu0010** [DO-NOTTO-DO/iOS-NOTTODO#138]
## 🍏 Issue

- 키보드 QA를 반영합니다.

## 📝 To-do

- [ ] 키보드 엔터키 수정
- [ ] 키보드 위 마진 수정
- [ ] 키보드 엔터 터치 시 토글 닫힘
