### ISSUE TITLE
[Fix] 생성/수정뷰 QA반영

### ISSUE THREAD

**Issue by yungu0010** [DO-NOTTO-DO/iOS-NOTTODO#159]
## 🍏 Issue

- 목표 토글 선택 위치 수정
- 날짜 선택 토글 UI 비활성화로 변경
- 한글 깨짐 현상 수정

## 📝 To-do

- [x] 목표 토글 선택 위치 수정
- [x] 날짜 선택 토글 UI 비활성화로 변경
- [x] 한글 깨짐 현상 수정
